# This is a basic workflow to help you get started with Actions

name: Build Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: SSH Command
       # You may pin to the exact commit or the version.
       # uses: D3rHase/ssh-command-action@3d8a11a6823dfe94f4fae068e6fc8b8f3d038c62
       uses: D3rHase/ssh-command-action@v0.2
       with:
         # hostname / IP of the server
         HOST: ${{ secrets.SSH_HOST }}
         # user of the server
         USER: ${{ secrets.SSH_USERNAME }}
         # private ssh key registered on the server
         PRIVATE_SSH_KEY: ${{ secrets.SSH_KEY }}
         # command to be executed
         COMMAND: cd /www/wwwroot/GameDocs/docs;gi pull;yarn git-build;

